web:
    build: ./centos7-nginx
    ports:
        - "80:80"
    volumes:
        - "/Users/Mac/Documents/projects/test:/var/www"
 #       - "/Users/Mac/Documents/projects/test/configs/nginx.conf:/etc/nginx/conf.d/host.conf"
    links:
        - php

php:
    build: ./centos7-php7.1-remi
    ports:
        - "9000:9000"
    volumes:
        - "/Users/Mac/Documents/projects/test:/var/www"
    links:
        - redis
        - mariadb

redis: 
    image: "centos/redis-32-centos7"
    ports:
        - "6379:6379"

mariadb:
    image: "mariadb"
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=root
